config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  mount ActionCable.server => '/cable'


  resources :messages
  resources :chat_rooms
  resources :precos
  resources :likes
  #devise_for :usuarios
  # config/routes.rb
  devise_for :usuarios, controllers: { registrations: 'registrations' }
  get 'usuario/conversas', to: "usuarios#conversas"
  get 'usuario/conversa/:chat_room', to: "usuarios#conversa"
  post 'usuario/conversa/:chat_room', to: "usuarios#post_conversa"
  resources :usuarios
  resources :anuncios
  resources :ponto_comercials
  root :to => 'anuncios#index' #seta maps#index para a primeira página do root
  #devise_for :users, :controllers => { :omniauth_callbacks => "callbacks_controller" }
  resources :maps
  # get '/route' => 'maps#maps_routes' #deixa visualizar maps_routes.html.erb
  # get '/publish' => 'ponto_comercials#new'#'maps#maps_publish' #deica visualizar maps_publish.html.erb
  # get '/near' => 'maps#maps_near' #deica visualizar maps_near.html.erb
  # get '/test' => 'maps#test' #teste com KML
  # get '/home' => 'ponto_comercials#home'
  # get '/pesquisa' => 'ponto_comercials#pesquisa'
  # get '/anuncio' => 'ponto_comercials#anuncio'
  # get '/cadastro' => 'ponto_comercials#cadastro'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'teste' => "anuncios#test"

  get 'usuario/:id/anuncios' => 'usuarios#anuncios', :as => :usuario_anuncios


  get "busca" => "anuncios#busca", :as => "busca"
  get "cod_sencitario/:id/:cod_sencitario" => "anuncios#cod_sencitario"
end

app/models/preco.rb
class Preco < ApplicationRecord
  belongs_to :anuncio
end

app/controllers/precos_controller.rb
class PrecosController < ApplicationController
  before_action :set_preco, only: [:show, :edit, :update, :destroy]

  # GET /precos
  # GET /precos.json
  def index
    @precos = Preco.all
  end

  # GET /precos/1
  # GET /precos/1.json
  def show
  end

  # GET /precos/new
  def new
    @preco = Preco.new
  end

  # GET /precos/1/edit
  def edit
  end

  # POST /precos
  # POST /precos.json
  def create
    @preco = Preco.new(preco_params)

    respond_to do |format|
      if @preco.save
        notification_price(Anuncio.find(@preco.anuncio_id))
        format.html { redirect_to anuncio_path(@preco.anuncio_id), notice: 'Preco was successfully created.' }
        format.json { render :show, status: :created, location: @preco }
      else
        format.html { render :new }
        format.json { render json: @preco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /precos/1
  # PATCH/PUT /precos/1.json
  def update
    respond_to do |format|
      if @preco.update(preco_params)
        format.html { redirect_to anuncio_path(@preco.anuncio_id), notice: 'Preco was successfully updated.' }
        format.json { render :show, status: :ok, location: @preco }
      else
        format.html { render :edit }
        format.json { render json: @preco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /precos/1
  # DELETE /precos/1.json
  def destroy
    @preco.destroy
    respond_to do |format|
      format.html { redirect_to precos_url, notice: 'Preco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preco
      @preco = Preco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preco_params
      params.require(:preco).permit(:preco_aluguel, :preco_venda, :preco_ponto, :preco_condominio, :preco_iptu, :preco_negociavel, :preco_outros, :preco_outros_descricao, :anuncio_id)
    end
end

app/helpers/precos_helper.rb
module PrecosHelper
end

app/views/precos/_form.html.erb
<%= form_for(preco) do |f| %>
  <% if preco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preco.errors.count, "error") %> prohibited this preco from being saved:</h2>

      <ul>
      <% preco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :preco_aluguel %>
    <%= f.text_field :preco_aluguel %>
  </div>

  <div class="field">
    <%= f.label :preco_venda %>
    <%= f.text_field :preco_venda %>
  </div>

  <div class="field">
    <%= f.label :preco_ponto %>
    <%= f.text_field :preco_ponto %>
  </div>

  <div class="field">
    <%= f.label :preco_condominio %>
    <%= f.text_field :preco_condominio %>
  </div>

  <div class="field">
    <%= f.label :preco_iptu %>
    <%= f.text_field :preco_iptu %>
  </div>

  <div class="field">
    <%= f.label :preco_negociavel %>
    <%= f.check_box :preco_negociavel %>
  </div>

  <div class="field">
    <%= f.label :preco_outros %>
    <%= f.text_field :preco_outros %>
  </div>

  <div class="field">
    <%= f.label :preco_outros_descricao %>
    <%= f.text_field :preco_outros_descricao %>
  </div>

  <div class="field">
    <%= f.label :anuncio_id %>
    <%= f.text_field :anuncio_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/precos/_form_new.html.erb
<% @anuncio = Anuncio.find(anuncio_id) %>
<%= form_for(preco) do |f| %>
  <% if preco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preco.errors.count, "error") %> prohibited this preco from being saved:</h2>

      <ul>
      <% preco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <label>Preço do Aluguel: <small>(R$)</small></label>
      <%= f.number_field :preco_aluguel, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Preço de Venda: <small>(R$)</small></label>
      <%= f.number_field :preco_venda, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Preço do Ponto: <small>(R$)</small></label>
      <%= f.number_field :preco_ponto, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Preço do Condomínio: <small>(R$)</small></label>
      <%= f.number_field :preco_condominio, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Preço do IPTU: <small>(R$)</small></label>
      <%= f.number_field :preco_iptu, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Preço é negociável?</label>
      <%= f.check_box :preco_negociavel, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Outros valores: <small>(R$)</small></label>
      <%= f.number_field :preco_outros, class: "form-control" %>
    </div>

    <div class="form-group">
      <label>Descrição dos outros valores: </label>
      <%= f.text_field :preco_outros_descricao, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.hidden_field :anuncio_id, value: anuncio_id %>
    </div>

    <div class="form-group">
      <%= f.submit 'Finalizar', class: "form-control" %>
    </div>

  </div>
  
<% end %>

app/views/precos/edit.html.erb
<h1>Editing Preco</h1>

<%= render 'form', preco: @preco %>

<%= link_to 'Show', @preco %> |
<%= link_to 'Back', precos_path %>

app/views/precos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Precos</h1>

<table>
  <thead>
    <tr>
      <th>Preco aluguel</th>
      <th>Preco venda</th>
      <th>Preco ponto</th>
      <th>Preco condominio</th>
      <th>Preco iptu</th>
      <th>Preco negociavel</th>
      <th>Preco outros</th>
      <th>Preco outros descricao</th>
      <th>Anuncio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @precos.each do |preco| %>
      <tr>
        <td><%= preco.preco_aluguel %></td>
        <td><%= preco.preco_venda %></td>
        <td><%= preco.preco_ponto %></td>
        <td><%= preco.preco_condominio %></td>
        <td><%= preco.preco_iptu %></td>
        <td><%= preco.preco_negociavel %></td>
        <td><%= preco.preco_outros %></td>
        <td><%= preco.preco_outros_descricao %></td>
        <td><%= preco.anuncio %></td>
        <td><%= link_to 'Show', preco %></td>
        <td><%= link_to 'Edit', edit_preco_path(preco) %></td>
        <td><%= link_to 'Destroy', preco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preco', new_preco_path %>

app/views/precos/new.html.erb
<style type="text/css">
		.navbar-header{
	      background-image: url(/assets/LOGO_AZUL_OFICIAL.png);
	      width: 200px;
	      background-size: 156px;
	      background-repeat: no-repeat;
	      background-position: 0px 6px;
	    }
	</style>
<!--    Linha verde     -->
<nav class="navbar navbar-default navbar-menu" id="navegacao" >
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed btn-color"
			data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/" style="color: #777;  width:100%;"></a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<% if @logged_in %>
					<li><%= link_to 'Agenda', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Favoritos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Meus Anuncios', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Anunciar' , new_anuncio_path, :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Alertas', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Mensagens', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Planos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<img src="/assets/engine3.png" style=" width: 19px; float: right; margin-top: 15px; margin-right: 20px;">
				<li class="dropdown menu-dropdown">
					<a href="#" class="dropdown-toggle menu-text"
						data-toggle="dropdown" role="button" aria-haspopup="true"
							aria-expanded="false" style="color: #777; font-size: 16px">
								<% if ! @logged_in %>
									Entrar
								<% else %>
									<%=current_usuario.nome%>
								<% end %>
							</span></a>
					<ul class="dropdown-menu">


						<% if ! @logged_in %>
							<li><%= link_to "Entrar", usuario_session_path %></li>
							<li><%= link_to "Cadastrar", new_usuario_registration_path%></li>

						<% else %>
							<li><%= link_to 'Perfil', usuario_path(current_usuario.id)%></li>
							<li><%= link_to 'Editar Perfil', edit_usuario_path(current_usuario.id) %></li>
							<li><%= link_to 'Sair', destroy_usuario_session_path, :method => :delete  %></li>
						<% end %>
						<li role="separator" class="divider"></li>

						<li><a href="#" class="menu-text">Ajuda</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>
<ol class="breadcrumb col-md-12" style="margin-left: 16.5vw; width: 82vw; text-align: left;">
				<li class="breadcrumb-item">Perfil</li>
				<li class="breadcrumb-item active">Cadastrar Anuncio</li>
</ol>




<%= render template: "layouts/side_menu.html.erb" %>
<div class="col-md-2">
</div>
<div class="col-md-10">
	<%= render 'form_new', preco: @preco, anuncio_id: params['anuncio'].to_i %>
</div>

app/views/precos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Preco aluguel:</strong>
  <%= @preco.preco_aluguel %>
</p>

<p>
  <strong>Preco venda:</strong>
  <%= @preco.preco_venda %>
</p>

<p>
  <strong>Preco ponto:</strong>
  <%= @preco.preco_ponto %>
</p>

<p>
  <strong>Preco condominio:</strong>
  <%= @preco.preco_condominio %>
</p>

<p>
  <strong>Preco iptu:</strong>
  <%= @preco.preco_iptu %>
</p>

<p>
  <strong>Preco negociavel:</strong>
  <%= @preco.preco_negociavel %>
</p>

<p>
  <strong>Preco outros:</strong>
  <%= @preco.preco_outros %>
</p>

<p>
  <strong>Preco outros descricao:</strong>
  <%= @preco.preco_outros_descricao %>
</p>

<p>
  <strong>Anuncio:</strong>
  <%= @preco.anuncio %>
</p>

<%= link_to 'Edit', edit_preco_path(@preco) %> |
<%= link_to 'Back', precos_path %>