config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  mount ActionCable.server => '/cable'


  resources :messages
  resources :chat_rooms
  resources :precos
  resources :likes
  #devise_for :usuarios
  # config/routes.rb
  devise_for :usuarios, controllers: { registrations: 'registrations' }
  get 'usuario/conversas', to: "usuarios#conversas"
  get 'usuario/conversa/:chat_room', to: "usuarios#conversa"
  post 'usuario/conversa/:chat_room', to: "usuarios#post_conversa"
  resources :usuarios
  resources :anuncios
  resources :ponto_comercials
  root :to => 'anuncios#index' #seta maps#index para a primeira página do root
  #devise_for :users, :controllers => { :omniauth_callbacks => "callbacks_controller" }
  resources :maps
  # get '/route' => 'maps#maps_routes' #deixa visualizar maps_routes.html.erb
  # get '/publish' => 'ponto_comercials#new'#'maps#maps_publish' #deica visualizar maps_publish.html.erb
  # get '/near' => 'maps#maps_near' #deica visualizar maps_near.html.erb
  # get '/test' => 'maps#test' #teste com KML
  # get '/home' => 'ponto_comercials#home'
  # get '/pesquisa' => 'ponto_comercials#pesquisa'
  # get '/anuncio' => 'ponto_comercials#anuncio'
  # get '/cadastro' => 'ponto_comercials#cadastro'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'teste' => "anuncios#test"

  get 'usuario/:id/anuncios' => 'usuarios#anuncios', :as => :usuario_anuncios


  get "busca" => "anuncios#busca", :as => "busca"
  get "cod_sencitario/:id/:cod_sencitario" => "anuncios#cod_sencitario"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :usuario
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:usuario_id, :visualizado, :conteudo)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario_id %>
    <%= f.text_field :usuario_id %>
  </div>

  <div class="field">
    <%= f.label :visualizado %>
    <%= f.check_box :visualizado %>
  </div>

  <div class="field">
    <%= f.label :conteudo %>
    <%= f.text_field :conteudo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Visualizado</th>
      <th>Conteudo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.usuario %></td>
        <td><%= notification.visualizado %></td>
        <td><%= notification.conteudo %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @notification.usuario %>
</p>

<p>
  <strong>Visualizado:</strong>
  <%= @notification.visualizado %>
</p>

<p>
  <strong>Conteudo:</strong>
  <%= @notification.conteudo %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>