config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  mount ActionCable.server => '/cable'


  resources :messages
  resources :chat_rooms
  resources :precos
  resources :likes
  #devise_for :usuarios
  # config/routes.rb
  devise_for :usuarios, controllers: { registrations: 'registrations' }
  get 'usuario/conversas', to: "usuarios#conversas"
  get 'usuario/conversa/:chat_room', to: "usuarios#conversa"
  post 'usuario/conversa/:chat_room', to: "usuarios#post_conversa"
  resources :usuarios
  resources :anuncios
  resources :ponto_comercials
  root :to => 'anuncios#index' #seta maps#index para a primeira página do root
  #devise_for :users, :controllers => { :omniauth_callbacks => "callbacks_controller" }
  resources :maps
  # get '/route' => 'maps#maps_routes' #deixa visualizar maps_routes.html.erb
  # get '/publish' => 'ponto_comercials#new'#'maps#maps_publish' #deica visualizar maps_publish.html.erb
  # get '/near' => 'maps#maps_near' #deica visualizar maps_near.html.erb
  # get '/test' => 'maps#test' #teste com KML
  # get '/home' => 'ponto_comercials#home'
  # get '/pesquisa' => 'ponto_comercials#pesquisa'
  # get '/anuncio' => 'ponto_comercials#anuncio'
  # get '/cadastro' => 'ponto_comercials#cadastro'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'teste' => "anuncios#test"

  get 'usuario/:id/anuncios' => 'usuarios#anuncios', :as => :usuario_anuncios


  get "busca" => "anuncios#busca", :as => "busca"
  get "cod_sencitario/:id/:cod_sencitario" => "anuncios#cod_sencitario"
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :anuncio
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.where(usuario: current_usuario.id)
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
    @usuarios = Usuario.all
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)
    @like.usuario = current_usuario.id if current_usuario
    @verify = Like.find_by(usuario: @like.usuario, anuncios_id: @like.anuncios_id)
    if !@verify.nil?
      @flag = true
    end

    respond_to do |format|
      if @flag
        @verify.destroy
        format.html { }
        format.json { }
      else
        anuncio = Anuncio.find(@like.anuncios_id)
        notification_like(anuncio)
        if @like.save
          format.html { redirect_to @like, notice: 'Like was successfully created.' }
          format.json { render :show, status: :created, location: @like }
        else
          format.html { render :new }
          format.json { render json: @like.errors, status: :unprocessable_entity }
        end
      end      
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      #params.fetch(:like, {})
      params.require(:like).permit(:usuario, :anuncios_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<script type="text/javascript">
$('#new_like').submit(function(e) {
    e.preventDefault();
    var valuesToSubmit = $(this).serialize();
    $.ajax({
        type: "POST",
        url: $(this).attr('action'), //sumbits it to the given url of the form
        data: valuesToSubmit,
        dataType: "JSON" // you want a difference between normal and ajax-calls, and json is standard
    }).success(function(json){
        console.log("success", json);
    });
    return false; // prevents normal behaviour
});
</script>

<%= form_for(like) do |f| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
      <%= f.select :anuncios_id, Anuncio.all.collect { |p| [ p.nome, p.id ] }, include_blank: true %>
    
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<%= stylesheet_link_tag    'all', media: 'all', 'data-turbolinks-track' => true %>
<style type="text/css">
  .navbar-header{
      background-image: url(/assets/LOGO_AZUL_OFICIAL.png);
      width: 200px;
      background-size: 156px;
      background-repeat: no-repeat;
      background-position: 0px 6px;
    }
</style>
<nav class="navbar navbar-default navbar-menu" id="navegacao" >
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed btn-color"
			data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/" style="color: #777;  width:100%;"></a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<% if @logged_in %>
					<li><%= link_to 'Agenda', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Favoritos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Meus Anuncios', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Anunciar' , new_anuncio_path, :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Alertas', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Mensagens', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Planos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<img src="/assets/engine3.png" style=" width: 19px; float: right; margin-top: 15px; margin-right: 20px;">
				<li class="dropdown menu-dropdown">
					<a href="#" class="dropdown-toggle menu-text"
						data-toggle="dropdown" role="button" aria-haspopup="true"
							aria-expanded="false" style="color: #777; font-size: 16px">
								<% if ! @logged_in %>
									Entrar
								<% else %>
									<%=current_usuario.nome%>
								<% end %>
							</span></a>
					<ul class="dropdown-menu">


						<% if ! @logged_in %>
							<li><%= link_to "Entrar", usuario_session_path %></li>
							<li><%= link_to "Cadastrar", new_usuario_registration_path%></li>

						<% else %>
							<li><%= link_to 'Perfil', usuario_path(current_usuario.id)%></li>
							<li><%= link_to 'Editar Perfil', edit_usuario_path(current_usuario.id) %></li>
							<li><%= link_to 'Sair', destroy_usuario_session_path, :method => :delete  %></li>
						<% end %>
						<li role="separator" class="divider"></li>

						<li><a href="#" class="menu-text">Ajuda</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>


<%= render template: "layouts/side_menu" %>



<style type="text/css">
  .profile{
    padding-top: 25vh;

  }
</style>
<ol class="breadcrumb col-md-12" style="margin-left: 16.5vw; width: 82vw; text-align: left;">
        <li class="breadcrumb-item">Perfil</li>
        <li class="breadcrumb-item active">Meus Favoritos</li>
  </ol>
<div class="col-md-2"></div>
<div class="col-md-10">
    <div class="row col-md-12" style="margin-bottom:50px;">
          <div class="row" style="margin-left:0px !important;">
            <div class="col-lg-12" style="text-align: start; margin-bottom: 10px;">
              <h4><b style="color: #8e8e8e;">Meus Favoritos</b></h4>
            </div><!-- col-lg-12 -->
          </div><!-- row -->
          <% if ! @likes.nil? %>
            <% @likes.each do |like| %>
            <% @valor = Preco.find_by(anuncio_id: like.anuncios_id)%>
              <%= link_to anuncio_path(like.anuncios_id) do %>
              <div class="col-lg-3" style="margin: 1px 30px; padding: 0;
                border:solid 1px #d2d2d2; background-image: url(/assets/SHOP.png);     height: 50vh;
                border-radius: 5px;
                background-position: 50px 19px;
                background-repeat: no-repeat;
                background-size: 150px;
                width: 40vh;">



                <div class="col-lg-3" style="    text-align: left;
                  margin-top: 27vh;
                  color: #868686;
                  border-top: solid 1px #d2d2d2;
                  width: 100%;
                  padding: 5px 1px 1px 10px;" >
                  <h4 style="color:#868686"><b>R$
                    <% if ! @valor.preco_aluguel.nil?%>
                      <%= '%.2f' % @valor.preco_aluguel%> <% end %></b></h4>
                    <p>R$ <% if ! @valor.preco_aluguel.nil?%>
                      <%= '%.2f' % @valor.preco_ponto%> <% end %> Luva/Ponto</p>
                  <p><%= Anuncio.find(like.anuncios_id).area_total %>M² |
                    <%= Anuncio.find(like.anuncios_id).qtd_ambientes %> ambientes</p>
                  <p><%= Anuncio.find(like.anuncios_id).logradouro %>
                     <%= Anuncio.find(like.anuncios_id).cidade %>, <%= Anuncio.find(like.anuncios_id).bairro %></p>
                    <p>  <b>Vende ou Aluga</b></p>
                </div>
                <!-- <p><i class="fa fa-link"></i> Leia mais</p> -->
              </div>

              <% end %>
            <% end %>
            <% else %>
              <h1>
                Não há anúncios.
              </h1>
          <% end %>






    </div><!-- row -->
</div>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<%= Usuario.find(@like.usuario).nome %>

<br>

<%=  Anuncio.find(@like.anuncios_id).nome %>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>