config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  mount ActionCable.server => '/cable'


  resources :messages
  resources :chat_rooms
  resources :precos
  resources :likes
  #devise_for :usuarios
  # config/routes.rb
  devise_for :usuarios, controllers: { registrations: 'registrations' }
  get 'usuario/conversas', to: "usuarios#conversas"
  get 'usuario/conversa/:chat_room', to: "usuarios#conversa"
  post 'usuario/conversa/:chat_room', to: "usuarios#post_conversa"
  resources :usuarios
  resources :anuncios
  resources :ponto_comercials
  root :to => 'anuncios#index' #seta maps#index para a primeira página do root
  #devise_for :users, :controllers => { :omniauth_callbacks => "callbacks_controller" }
  resources :maps
  # get '/route' => 'maps#maps_routes' #deixa visualizar maps_routes.html.erb
  # get '/publish' => 'ponto_comercials#new'#'maps#maps_publish' #deica visualizar maps_publish.html.erb
  # get '/near' => 'maps#maps_near' #deica visualizar maps_near.html.erb
  # get '/test' => 'maps#test' #teste com KML
  # get '/home' => 'ponto_comercials#home'
  # get '/pesquisa' => 'ponto_comercials#pesquisa'
  # get '/anuncio' => 'ponto_comercials#anuncio'
  # get '/cadastro' => 'ponto_comercials#cadastro'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'teste' => "anuncios#test"

  get 'usuario/:id/anuncios' => 'usuarios#anuncios', :as => :usuario_anuncios


  get "busca" => "anuncios#busca", :as => "busca"
  get "cod_sencitario/:id/:cod_sencitario" => "anuncios#cod_sencitario"
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable #:confirmable,
  has_many :anuncio, dependent: :destroy
  #before_action :verify_authenticity_token, :only => [:index]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |usuario|
      usuario.email = auth.info.email
      usuario.name = auth.info.name
      usuario.password = Devise.friendly_token[0,20]
      usuario.image = auth.info.image
    end
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, only: [:index, :show, :edit, :update, :destroy, :anuncios]

  def conversas
    @conversas = ChatRoom.where(usuario_id: current_usuario.id).or(ChatRoom.where(usuario2_id: current_usuario.id))    
  end

  def conversa
    @mensagens = Message.where(ChatRoom_id: params[:chat_room])
    @mensagem = Message.new
    respond_to do |format|
      format.html { render "conversa" }
      format.json { render json: @mensagens}
    end
  end
  def post_conversa
    
  end

  def anuncios
    @anuncios = Anuncio.where(:usuario_id => current_usuario.id)
    @notificacoes = Notification.where(usuario_id: current_usuario.id, visualizado: false)
  end

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :data_nascimento, :sexo, :telefone, :email, :senha, :rua, :bairro, :cidade, :estado)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= javascript_include_tag 'utils.js'%>
<%= stylesheet_link_tag    'all', media: 'all', 'data-turbolinks-track' => true %>
<%= form_for(usuario) do |f| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-12">
  <div class="row" style="margin-left:0px !important;">
    <div class="col-lg-12" style="text-align: start; margin-bottom: 10px;">
      <h4><b style="color: #8e8e8e;">Cadastro</b></h4>
    </div><!-- col-lg-12 -->
  </div><!-- row -->
    <div class="col-md-6">
        <div class="form">
            <div class="form-group">
                <%= f.label :email %>
                <%= f.text_field :email, placeholder: "email@exemplo.com", class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :senha %>
                <%= f.password_field :senha, placeholder: "Senha", class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :nome %>
                <%= f.text_field :nome, placeholder: "Nome Sobrenome", class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :data_nascimento%>
                <br>
                <%= f.date_select(:data_nascimento, options = { :order => [:year, :month, :day ], :use_month_names=>["Janeiro" ,"Fevereiro", "Março", "Abril" ,"Maio", "Junho","Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" ],:start_year => 1900, :end_year => Time.now.year}, html_options = { :class=> "form-control", :style=>"width: 30% !important; float: right;"}) %>
                <br>
            </div>

            <div class="form-group">
                <%= f.label :sexo %>
                <br>
                <label class="btn btn-primary btn-lg btn-block btn-color">
                    <%= f.radio_button :sexo, 'Masculino' %>Masculino
                </label>
                <label class="btn btn-primary btn-lg btn-block btn-color">
                    <%= f.radio_button :sexo, 'Feminino' %>Feminino
                </label>
                <label class="btn btn-primary btn-lg btn-block btn-color">
                    <%= f.radio_button :sexo, 'Outros' %>Outros
                </label>
            </div>

            <div class="form-group">
                <%= f.label :telefone %>
                <%= f.number_field :telefone, placeholder: "99 9 99999999", class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :rua %>
                <%= f.text_field :rua, placeholder: "Rua Exemplo", class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :bairro %>
                <%= f.text_field :bairro, placeholder: "Bairro", class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :cidade %>
                <%= f.text_field :cidade, placeholder: "Cidade", class: "form-control" %>
            </div>

            <div class="form-group">
                <%= f.label :estado %>
                <%= f.text_field :estado, placeholder: "Estado", class: "form-control" %>
            </div>
        </div>
        <div class="form-group">
            <%= f.submit "Cadastrar", :class => " form-control btn-primary btn-lg btn-color"%>
        </div>
    </div>
    <div class="col-md-3">
    </div>

</div>



<% end %>

app/views/usuarios/anuncios.html.erb
<%= stylesheet_link_tag    'all', media: 'all', 'data-turbolinks-track' => true %>
<style type="text/css">
  .navbar-header{
      background-image: url(/assets/LOGO_AZUL_OFICIAL.png);
      width: 200px;
      background-size: 156px;
      background-repeat: no-repeat;
      background-position: 0px 6px;
    }
</style>
<nav class="navbar navbar-default navbar-menu" id="navegacao" >
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed btn-color"
			data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/" style="color: #777;  width:100%;"></a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<% if @logged_in %>
					<li><%= link_to 'Agenda', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Favoritos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Meus Anuncios', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Anunciar' , new_anuncio_path, :class => "menu-text", :style => "color: #777"%></li>
					<li><button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Alertas
          <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <% for notificacao in @notificacoes %>
            <hr>
            <li><%= notificacao.conteudo.html_safe %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="#">Todas Notificações</a></li>
          </ul>     
          </li>
					<li><%= link_to 'Mensagens', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Planos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<img src="/assets/engine3.png" style=" width: 19px; float: right; margin-top: 15px; margin-right: 20px;">
				<li class="dropdown menu-dropdown">
					<a href="#" class="dropdown-toggle menu-text"
						data-toggle="dropdown" role="button" aria-haspopup="true"
							aria-expanded="false" style="color: #777; font-size: 16px">
								<% if ! @logged_in %>
									Entrar
								<% else %>
									<%=current_usuario.nome%>
								<% end %>
							</span></a>
					<ul class="dropdown-menu">


						<% if ! @logged_in %>
							<li><%= link_to "Entrar", usuario_session_path %></li>
							<li><%= link_to "Cadastrar", new_usuario_registration_path%></li>

						<% else %>
							<li><%= link_to 'Perfil', usuario_path(current_usuario.id)%></li>
							<li><%= link_to 'Editar Perfil', edit_usuario_path(current_usuario.id) %></li>
							<li><%= link_to 'Sair', destroy_usuario_session_path, :method => :delete  %></li>
						<% end %>
						<li role="separator" class="divider"></li>

						<li><a href="#" class="menu-text">Ajuda</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>
<%= render template: "layouts/side_menu" %>
<style type="text/css">
  .profile{
    padding-top: 25vh;

  }
</style>
<ol class="breadcrumb col-md-12" style="margin-left: 16.5vw; width: 82vw; text-align: left;">
        <li class="breadcrumb-item">Perfil</li>
        <li class="breadcrumb-item active">Meus Anúncios</li>
  </ol>
<div class="col-md-2"></div>
<div class="col-md-10" style="margin-bottom: 50px;">
    <div class="row col-md-8">
          <div class="row" style="margin-left:0px !important;">
            <div class="col-lg-12" style="text-align: start; margin-bottom: 10px;">
              <h4><b style="color: #8e8e8e;">Meus Anúncios</b></h4>
            </div><!-- col-lg-12 -->
          </div><!-- row -->
          <% if ! @anuncios.nil? %>
            <% @anuncios.each do |anuncio| %>
            	<% @valores = Preco.find_by(anuncio_id: anuncio.id)%>
              <%= link_to(anuncio) do %>
              <div class="col-lg-3" style="margin: 1px 30px; padding: 0;
                border:solid 1px #d2d2d2; background-image: url(/assets/SHOP.png);     height: 50vh;
                border-radius: 5px;
                background-position: 50px 19px;
                background-repeat: no-repeat;
                background-size: 150px;
                width: 40vh;">



                <div class="col-lg-3" style="    text-align: left;
                  margin-top: 27vh;
                  color: #868686;
                  border-top: solid 1px #d2d2d2;
                  width: 100%;
                  padding: 5px 1px 1px 10px;" >
                  <h4 style="color:#868686"><b>R$ <%= (!@valores.nil? ? (anuncio.pretencao == "Vender" ? @valores.preco_venda : (anuncio.pretencao == "Alugar" ? @valores.preco_aluguel : @valores.preco_venda)) : "") %></b></h4>
                  	
                    <p><%= (!@valores.nil? ? (!@valores.preco_ponto.nil? ? ("R$ " + @valores.preco_ponto.to_s + " Ponto") : "") : "") %></p>
                  <p><%= anuncio.area_total %>M² | <%= anuncio.qtd_ambientes %> ambientes</p>
                  <p><%= anuncio.logradouro %> <%= anuncio.cidade %>, <%= anuncio.bairro %></p>
                  <p>  <b><%= anuncio.pretencao %></b></p>
                </div>
                <!-- <p><i class="fa fa-link"></i> Leia mais</p> -->
                <hr>
                <div>
                  <%= link_to "Excluir", anuncio, method: :delete, data: { confirm: 'Ao continuar você exluirá permanentemente todos os dados relacionados à este enúncio. Continuar?' } %>
                  |<%= link_to 'Editar Anúncio', edit_anuncio_path(anuncio) %>
                  |<a href="/precos/new?anuncio=<%=anuncio.id%>">Alterar Preço</a>
                </div>
              </div>

              <% end %>
            <% end %>
            <% else %>
              <h1>
                Não há anúncios.
              </h1>
          <% end %>

    </div><!-- row -->
</div>

app/views/usuarios/conversa.html.erb
<div class="row" id="mensagens">
	<div class="col-md-4 col-md-offset-4">
		<% for mensagem in @mensagens %>
			<% if mensagem.usuario_id == current_usuario.id %>
				<div class="col-md-12 text-right">
					<h3><%= mensagem.conteudo %></h3>				
				</div>
			<% else %>
				<div class="col-md-12">
					<h3><%= mensagem.conteudo %></h3>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<%= form_for(@mensagem, remote: true) do |f| %>
		<%= f.hidden_field :usuario_id, value: current_usuario.id %>
		<%= f.hidden_field :ChatRoom_id, value: params[:chat_room] %>

		  <div class="field">
		    <label>Mensagem:</label>
		    <%= f.text_area :conteudo %>
		  </div>

		  <div class="actions">
		    <%= f.submit "Enviar", class: "btn" %>
		  </div>
		<% end %>
	</div>	
</div>

app/views/usuarios/conversa.js.erb
$("mensagens").append(<%= j render @message %>)

app/views/usuarios/conversas.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<% for conversa in @conversas %>
			<a href="/usuario/conversa/<%=conversa.id%>">
				<% if current_usuario.id == conversa.usuario_id %>
					<%= Usuario.find(conversa.usuario2_id).nome %>
				<% else %>
					<%= Usuario.find(conversa.usuario_id).nome %>
				<% end %>
			</a>
		<% end %>
	</div>
</div>

app/views/usuarios/edit.html.erb
<%= render template: "layouts/side_menu" %>
<style type="text/css">

</style>
<style type="text/css">
    .profile{
		padding-top: 35vh;
		
	}
</style>
<style type="text/css">
  .navbar-header{
      background-image: url(/assets/LOGO_AZUL_OFICIAL.png);
      width: 200px;
      background-size: 156px;
      background-repeat: no-repeat;
      background-position: 0px 6px;
    }
</style>
<nav class="navbar navbar-default navbar-menu" id="navegacao" >
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed btn-color"
			data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/" style="color: #777;  width:100%;"></a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<% if @logged_in %>
					<li><%= link_to 'Agenda', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Favoritos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Meus Anuncios', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Anunciar' , new_anuncio_path, :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Alertas', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Mensagens', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
					<li><%= link_to 'Planos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
				<% end %>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<img src="/assets/engine3.png" style=" width: 19px; float: right; margin-top: 15px; margin-right: 20px;">
				<li class="dropdown menu-dropdown">
					<a href="#" class="dropdown-toggle menu-text"
						data-toggle="dropdown" role="button" aria-haspopup="true"
							aria-expanded="false" style="color: #777; font-size: 16px">
								<% if ! @logged_in %>
									Entrar
								<% else %>
									<%=current_usuario.nome%>
								<% end %>
							</span></a>
					<ul class="dropdown-menu">


						<% if ! @logged_in %>
							<li><%= link_to "Entrar", usuario_session_path %></li>
							<li><%= link_to "Cadastrar", new_usuario_registration_path%></li>

						<% else %>
							<li><%= link_to 'Perfil', usuario_path(current_usuario.id)%></li>
							<li><%= link_to 'Editar Perfil', edit_usuario_path(current_usuario.id) %></li>
							<li><%= link_to 'Sair', destroy_usuario_session_path, :method => :delete  %></li>
						<% end %>
						<li role="separator" class="divider"></li>

						<li><a href="#" class="menu-text">Ajuda</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

      	<div class="col-md-2"></div>
		<div class="col-md-10">

			<ol class="breadcrumb col-md-12" style="margin-left: -1vw; width: 82vw;">
			  <li class="breadcrumb-item">Perfil</li>
			  <li class="breadcrumb-item active">Editar</li>
			</ol>

				<%= render 'form_edit', usuario: @usuario %>
		</div>
      </div>

app/views/usuarios/facebook.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Hello World</h1>
</body>
</html>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data nascimento</th>
      <th>Sexo</th>
      <th>Telefone</th>
      <th>Email</th>
      <th>Senha</th>
      <th>Rua</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.data_nascimento %></td>
        <td><%= usuario.sexo %></td>
        <td><%= usuario.telefone %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.senha %></td>
        <td><%= usuario.rua %></td>
        <td><%= usuario.bairro %></td>
        <td><%= usuario.cidade %></td>
        <td><%= usuario.estado %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<center>
	<h1>Cadastro</h1>
</center>




<%= render 'form', usuario: @usuario %>

app/views/usuarios/show.html.erb
<%= stylesheet_link_tag    'all', media: 'all', 'data-turbolinks-track' => true %>

<style type="text/css">
  .navbar-header{
      background-image: url(/assets/LOGO_AZUL_OFICIAL.png);
      width: 200px;
      background-size: 156px;
      background-repeat: no-repeat;
      background-position: 0px 6px;
    }
</style>
<nav class="navbar navbar-default navbar-menu" id="navegacao" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed btn-color"
      data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="color: #777;  width:100%;"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if @logged_in %>
          <li><%= link_to 'Agenda', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
          <li><%= link_to 'Favoritos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
          <li><%= link_to 'Meus Anuncios', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
          <li><%= link_to 'Anunciar' , new_anuncio_path, :class => "menu-text", :style => "color: #777"%></li>
          <li><%= link_to 'Alertas', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
          <li><%= link_to 'Mensagens', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
          <li><%= link_to 'Planos', usuario_anuncios_path(current_usuario.id), :class => "menu-text", :style => "color: #777"%></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <img src="/assets/engine3.png" style=" width: 19px; float: right; margin-top: 15px; margin-right: 20px;">
        <li class="dropdown menu-dropdown">
          <a href="#" class="dropdown-toggle menu-text"
            data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false" style="color: #777; font-size: 16px">
                <% if ! @logged_in %>
                  Entrar
                <% else %>
                  <%=current_usuario.nome%>
                <% end %>
              </span></a>
          <ul class="dropdown-menu">


            <% if ! @logged_in %>
              <li><%= link_to "Entrar", usuario_session_path %></li>
              <li><%= link_to "Cadastrar", new_usuario_registration_path%></li>

            <% else %>
              <li><%= link_to 'Perfil', usuario_path(current_usuario.id)%></li>
              <li><%= link_to 'Editar Perfil', edit_usuario_path(current_usuario.id) %></li>
              <li><%= link_to 'Sair', destroy_usuario_session_path, :method => :delete  %></li>
            <% end %>
            <li role="separator" class="divider"></li>

            <li><a href="#" class="menu-text">Ajuda</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <%= render template: "layouts/side_menu" %>

  <style type="text/css">
    .profile{
      padding-top: 25vh;
    }
  </style>

  <ol class="breadcrumb col-md-12" style="margin-left: 16.5vw; width: 82vw; text-align: left;">
        <li class="breadcrumb-item">Perfil</li>
        <li class="breadcrumb-item active">Visualizar</li>
  </ol>
  <div class="col-md-2"></div>


  <!--    Content     -->
  <div class="col-md-10" style="text-align: center; height: 100vh;padding-top: 10vh;">

      <section class="col-md-6">
          <header>
              <h3>Pessoal</h3>
          </header>
          <article>
              <p>
                <strong>Nome:</strong>
                <%= @usuario.nome %>
              </p>

              <p>
                <strong>Data nascimento:</strong>
                <%= @usuario.data_nascimento %>
              </p>

              <p>
                <strong>Sexo:</strong>
                <%= @usuario.sexo %>
              </p>

              <p>
                <strong>Telefone:</strong>
                <%= @usuario.telefone %>
              </p>

              <p>
                <strong>Email:</strong>
                <%= @usuario.email %>
              </p>
          </article>
      </section>
      <section class="col-md-6">
          <header>
              <h3>Endereço</h3>
          </header>
          <article>
              <p>
                <strong>Rua:</strong>
                <%= @usuario.rua %>
              </p>

              <p>
                <strong>Bairro:</strong>
                <%= @usuario.bairro %>
              </p>

              <p>
                <strong>Cidade:</strong>
                <%= @usuario.cidade %>
              </p>

              <p>
                <strong>Estado:</strong>
                <%= @usuario.estado %>
              </p>
          </article>
      </section>
      <div class="col-md-12">
        <center>
          <%= link_to 'Mudar Senha', edit_usuario_registration_path, :class => "btn btn-color", :style => "color: #FFF;" %>
        </center>
      </div>

  </div>
  <!--    END     Content     -->


<div class="col-md-2"></div>